### ISSUE TITLE
Problems with test task

### ISSUE THREAD

**Issue by ElForastero** [DZDeemix/testRadyushin2#1]
- [x] Must be written in PHP 7, using its benefits (7.3 is highly appreciated).
- [ ] No need to prefix private fields with unrerscore.
- [ ] With `mysqli_*` functions you are strongly depend on MySQL. PDO should be used instead.
- [ ] No prepared queries, nor escaped params. Code is petentially vulnerable to SQL injections.
- [ ] View logic is mixed with Database queries. Not a good practice.
- [ ] Queries are almost the same - base table + two joins. Better to extract them into some model/builder.
- [ ] Would be better if getSimilarAuthors will be done with subquery, limilar to you already had.

**Comment by DZDeemix** [comment]
No need to prefix private fields with unrerscore.
In PSR2 yes, but PEAR standard requires it. Corrected to standard PSR2.
The remaining issues are also corrected.
8a932513d5e082f27ddbb77feaeca46c4eea4462
